#!/bin/sh
cd / >/dev/null
patch -Np1 -i /usr/local/https-mirrors/https-mirrors.patch

if [ -L /usr/local/share/mirrors ]; then
	rm /usr/local/share/mirrors
	cp /tmp/tcloop/mirrors/usr/local/share/mirrors /usr/local/share/mirrors
fi

if [ -e /usr/local/share/mirrors ]; then
	cat <<EOF >>/usr/local/share/mirrors
https://distro.ibiblio.org/tinycorelinux/
https://ftp.nluug.nl/os/Linux/distr/pub/linux/distributions/tinycorelinux/
https://sunsite.icm.edu.pl/pub/Linux/sunsite.unc.edu/distributions/tinycorelinux/
https://sunsite2.icm.edu.pl/pub/Linux/sunsite.unc.edu/distributions/tinycorelinux/
https://mirror.cedia.org.ec/tinycorelinux/
https://mirrors.dotsrc.org/tinycorelinux/
https://mirrors.163.com/tinycorelinux/
EOF
fi

cd - >/dev/null
